name: CI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: |
          sudo apt update
          sudo apt install wine64
          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32:i386
      - id: extract_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.0-dev" >> $GITHUB_OUTPUT
          fi
      - run: |
          VERSION=${{ steps.extract_tag.outputs.version }}
          jq --arg v "$VERSION" '.version = $v' package.json > tmp.json && mv tmp.json package.json
      - run: |
          npm run dist
          sleep 2  # EXE生成後のI/O待ち
      - run: |
          VERSION=${{ steps.extract_tag.outputs.version }}
          ls dist
          mv dist/win-unpacked dist/task-manage-$VERSION
          cd dist && tar -cvzf task-manage-$VERSION.tar.gz task-manage-$VERSION
          sleep 2  # tar.gz生成後のI/O待ち

      # .tar.gzのみアップロード
      - uses: softprops/action-gh-release@v2.0.4
        with:
          name: Release v${{ steps.extract_tag.outputs.version }}
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # .exeのみアップロード
      - uses: softprops/action-gh-release@v2.0.4
        with:
          name: Release v${{ steps.extract_tag.outputs.version }}
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
